"""
Canonical Pydantic Schemas for Phase 5 RAG Builder Subsystem.
Strict validation with extra='forbid' to preserve data integrity across pipeline stages.
"""

from datetime import datetime, timezone
from enum import Enum
import hashlib
import json
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class BuildStage(str, Enum):
    """Distinct observable stages of the build execution pipeline."""

    IDLE = "idle"
    PREFLIGHT = "preflight"
    CHUNKING = "chunking"
    EMBEDDING = "embedding"
    INDEXING = "indexing"
    VERIFYING = "verifying"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCEL_REQUESTED = "cancel_requested"
    CANCELLED = "cancelled"


class ChunkType(str, Enum):
    """Classification of chunk for retrieval and context assembly."""

    STANDARD_PARAGRAPH = "standard_paragraph"
    CHILD_CHUNK = "child_chunk"
    PARENT_CHUNK = "parent_chunk"
    TABULAR_ROW = "tabular_row"
    TABULAR_SCHEMA = "tabular_schema"
    SECTION_BLOCK = "section_block"


class ChunkMetadata(BaseModel):
    """Structured, provenance-preserving metadata attached to each chunk."""

    model_config = ConfigDict(extra="forbid")

    source_id: str
    source_name: str
    chunk_index: int = Field(ge=0)
    token_count: int = Field(ge=1)
    page_number: Optional[int] = Field(default=None, ge=1)
    sheet_name: Optional[str] = None
    heading_path: List[str] = Field(default_factory=list)
    parent_chunk_id: Optional[str] = None
    model_type: str = "document"
    extra: Dict[str, Any] = Field(default_factory=dict)


class Chunk(BaseModel):
    """Normalized searchable unit of knowledge generated by chunking engine."""

    model_config = ConfigDict(extra="forbid")

    chunk_id: str
    source_id: str
    text: str = Field(min_length=1)
    chunk_type: ChunkType
    metadata: ChunkMetadata
    token_count: int = Field(ge=1)


class SourceSnapshot(BaseModel):
    """Immutable preflight snapshot of a registered source for integrity verification."""

    model_config = ConfigDict(extra="forbid")

    source_id: str
    sha256: str
    model_type: str
    file_path: str


class BuildProgress(BaseModel):
    """Real-time observable telemetry emitted during build pipeline execution."""

    model_config = ConfigDict(extra="forbid")

    build_id: Optional[str] = None
    status: str = "idle"
    current_stage: BuildStage = BuildStage.IDLE
    chunks_total: int = Field(default=0, ge=0)
    chunks_processed: int = Field(default=0, ge=0)
    vectors_total: int = Field(default=0, ge=0)
    vectors_processed: int = Field(default=0, ge=0)
    embedding_dimension: int = Field(default=0, ge=0)
    elapsed_seconds: float = Field(default=0.0, ge=0.0)
    error_code: Optional[str] = None
    message: Optional[str] = None
    log_messages: List[str] = Field(default_factory=list)


class BuildManifest(BaseModel):
    """
    Immutable build receipt generated upon successful completion of the pipeline.
    Serves as the cryptographic and operational foundation for retrieval and audit.
    """

    model_config = ConfigDict(extra="forbid")

    manifest_id: str
    workspace_id: str
    build_id: str
    config_id: str
    config_version: int
    config_hash: str
    source_ids: List[str]
    source_hashes: Dict[str, str]
    approved_architecture: str
    chunking_config: Dict[str, Any]
    embedding_config: Dict[str, Any]
    vector_db_config: Dict[str, Any]
    retrieval_config: Dict[str, Any]
    chunk_count: int = Field(ge=1)
    vector_count: int = Field(ge=1)
    embedding_dimension: int = Field(ge=1)
    embedding_model: str
    vector_store: str
    started_at: datetime
    completed_at: datetime
    build_duration_ms: float = Field(ge=0.0)
    manifest_hash: str
    status: str = "completed"

    @classmethod
    def compute_manifest_hash(cls, payload: Dict[str, Any]) -> str:
        """Computes deterministic SHA-256 digest of manifest contents, excluding manifest_hash."""
        filtered = {k: v for k, v in payload.items() if k != "manifest_hash"}
        for key in ["started_at", "completed_at"]:
            if key in filtered and isinstance(filtered[key], datetime):
                filtered[key] = filtered[key].isoformat()
        canonical_json = json.dumps(filtered, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical_json.encode("utf-8")).hexdigest()
